apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          resources:
            limits:
              memory: "1500Mi"
              cpu: "600m"
            requests:
              memory: "400Mi"
              cpu: "300m"
          image: abhithshaji/landapp-frontend:1.8

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: ClusterIP
  ports:
    - name: "frontend"
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    name: frontend
