apiVersion: v1
kind: Service
metadata:
  name: ca-sro
  labels:
    app: ca-sro
spec:
  type: ClusterIP
  selector:
    app: ca-sro
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054