--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: fabland-sro
  labels:
    app: fabland-sro
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-fabland-sro
