---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-fabland-sro
  labels:
    app: chaincode-fabland-sro
spec:
  selector:
    matchLabels:
      app: chaincode-fabland-sro
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-fabland-sro
    spec:
      containers:
        - image: abhithshaji/fabland:2.1
          imagePullPolicy: Always
          name: chaincode-fabland-sro
          env:
            - name: CHAINCODE_ID
              value: "fabland:2cc3affe748a554ed496414d600e74f96fb1d00f25df7378b935e8c83ef48a36"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
