---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-dealer
  labels:
    app: chaincode-basic-dealer
spec:
  selector:
    matchLabels:
      app: chaincode-basic-dealer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-dealer
    spec:
      containers:
        - image: abhithshaji/automobile:2.3
          name: chaincode-basic-dealer
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:c0a455822af0328aed6d7beffd4af07cb36efe3950dca2461e36755883c6376d"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
