---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-manufacturer
  labels:
    app: chaincode-basic-manufacturer
spec:
  selector:
    matchLabels:
      app: chaincode-basic-manufacturer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-manufacturer
    spec:
      containers:
        - image: abhithshaji/automobile:2.3
          imagePullPolicy: Always
          name: chaincode-basic-manufacturer
          env:
            - name: CHAINCODE_ID
              value: "basic:798e433c6b461c2dfdb6074cdaa8875a678fa9db0279864d37d4c95c78000c69"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
