apiVersion: v1
kind: Service
metadata:
  name: ca-bank
  labels:
    app: ca-bank
spec:
  type: ClusterIP
  selector:
    app: ca-bank
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054