apiVersion: v1
kind: Service
metadata:
  name: ca-revenue
  
  labels:
    app: ca-revenue
spec:
  type: ClusterIP
  selector:
    app: ca-revenue
  ports:
    - protocol: TCP
      targetPort: 9054
      port: 9054