apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    app: nginx-app
    type: frontend
spec:
  template:
    metadata: 
      name: nginx-pod
      labels:
        app: nginx-app
        type: frontend
    spec:
      containers:
        -  name: nginx-container
           image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: frontend