---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-fabland-revenue
  labels:
    app: chaincode-fabland-revenue
spec:
  selector:
    matchLabels:
      app: chaincode-fabland-revenue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-fabland-revenue
    spec:
      containers:
        - image: abhithshaji/fabland:2.1
          name: chaincode-fabland-revenue
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "fabland:7d4c77810d67e7fae3241d9af189a10e13fb25294953c32de206e4e918fa2f9e"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
